# Generated by Django 5.2.4 on 2025-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOutage',
            fields=[
                ('outage_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('customers_affected', models.IntegerField()),
                ('eta', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'active_outages',
            },
        ),
    ]
